### ISSUE TITLE
Bot crashed on giveaway with ID 29862

### ISSUE THREAD

**Issue by johnlx86** [lukasmoldon/astats-bot#3]
As the title says the bot crashes at giveaway ID 29862. I visited the corresponding webpage (https://astats.astats.nl/astats/Giveaway.php?GiveawayID=29862): "Cannot join - This giveaway has not yet started.". So I guess I can not join the giveaway, but the bot clearly should not stop at this point as there are other giveaways continuing at 29863.

**Comment by lukasmoldon** [comment]
Fixed in e44520e517dcfa9ae490bbbb449f8454a76a3726

Thank you for reporting!
