### ISSUE TITLE
Bot crashes with "unknown reason" at giveaway IDs 30012, 30013 and 30014

### ISSUE THREAD

**Issue by johnlx86** [lukasmoldon/astats-bot#4]
Hi Lukas,

I once again have the issue of an "unknown reason" crash at giveaways with IDs 30012, 30013 and 30014. I visited the corresponding webpages like last time (e.g. https://astats.astats.nl/astats/Giveaway.php?GiveawayID=30012):

"Join requirements:
1000 AStats points
Not owning the game already."

Since I do not own the games, I think the issue is related to the AStats points threshold?

**Comment by lukasmoldon** [comment]
Fixed in 73146f250d46320d080efea956f0e4261d2f7276

Thanks for reporting!
